### ISSUE TITLE
Username,Password logging in?

### ISSUE THREAD

**Issue by TDBOfficial** [Jegarde/RecNet-Login#10]
i used this back in 2022 and now it doesnt support username and password logging in?
Seems to kinda just remove the point because if you care enough to use this you can just get your token from your browser yourself

**Comment by Jegarde** [comment]
Because of the new CAPTCHA in the login page, you're no longer able to login externally with your account credentials. You can blame RR for breaking the old version of RecNetLogin.

I get your point about just getting the token from the browser, but it only lasts an hour. With this module you only have to get the cookie roughly once every 2 weeks and the token works across all your Python programs automatically. Whether or not you find that practical is up to you.
